### ISSUE TITLE
StackTrace from Logs

### ISSUE THREAD

**Issue by samiona2** [magicsunday/webtrees-fan-chart#103]
I am unsure what is triggering this or how to replicate since it seems to work for me, but I see the following in the logs.

```
webtrees-fan-chart …/vendor/aura/router/src/Map.php:169
 #0 …/vendor/aura/router/src/Map.php(218): Aura\Router\Map-&gt;addRoute(Object(Aura\Router\Route))
 #1 …/vendor/aura/router/src/Map.php(241): Aura\Router\Map-&gt;route(&#039;webtrees-fan-ch...&#039;, &#039;/tree/{tree}/we...&#039;, Object(MagicSunday\Webtrees\FanChart\Module)) <b>#2 …/modules_v4/webtrees-fan-chart/src/Module.php(107): Aura\Router\Map-&gt;get(&#039;webtrees-fan-ch...&#039;, &#039;/tree/{tree}/we...&#039;, Object(MagicSunday\Webtrees\FanChart\Module))</b>
 #3 …/app/Services/ModuleService.php(925): MagicSunday\Webtrees\FanChart\Module-&gt;boot()
 #4 …/app/Http/Middleware/BootModules.php(56): Fisharebest\Webtrees\Services\ModuleService-&gt;bootModules(Object(Fisharebest\Webtrees\Module\WebtreesTheme))
 #5 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #6 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #8 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #9 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #10 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #12 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #13 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
 #14 …/app/Http/Middleware/UseTransaction.php(44): Illuminate\Database\Connection-&gt;transaction(Object(Closure), 3)
 #15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #16 …/app/Http/Middleware/DoHousekeeping.php(71): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #18 …/app/Http/Middleware/UseTheme.php(67): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #20 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #22 …/app/Http/Middleware/UseLanguage.php(69): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #24 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #26 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #28 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #30 …/app/Http/Middleware/BadBotBlocker.php(293): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #32 …/app/Http/Middleware/CompressResponse.php(71): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #34 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #36 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #37 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #39 …/app/Http/Middleware/HandleExceptions.php(89): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #41 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #43 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #45 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #46 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #47 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
 #49 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher-&gt;handle(Object(Nyholm\Psr7\ServerRequest))
 #50 …/app/Webtrees.php(275): Middleland\Dispatcher-&gt;dispatch(Object(Nyholm\Psr7\ServerRequest))
 #51 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
 #52 …/index.php(51): Fisharebest\Webtrees\Webtrees-&gt;httpRequest()
 #53 {main}
```

**Comment by magicsunday** [comment]
Please follow the error reporting template to report any errors. Without the necessary information I can't do anything with the stack trace. Furthermore, please describe in detail how, where and when the error occurs so that it can be reproduced.

**Comment by HRN65** [comment]
Sorry, for not adding more information. The posting has now been updated.

Thank you for great work!

Hogne Røed Nilsen
________________________________
Fra: Rico Sonntag ***@***.***>
Sendt: torsdag 28. mars 2024 10:00
Til: magicsunday/webtrees-fan-chart ***@***.***>
Kopi: Subscribed ***@***.***>
Emne: Re: [magicsunday/webtrees-fan-chart] StackTrace from Logs (Issue #103)


Please follow the error reporting template to report any errors. Without the necessary information I can't do anything with the stack trace. Furthermore, please describe in detail how, where and when the error occurs so that it can be reproduced.

**Comment by magicsunday** [comment]
Feel free to reopen this issue if you still got problems.
