### ISSUE TITLE
Error in 2.3.0

### ISSUE THREAD

**Issue by Fa10175** [magicsunday/webtrees-fan-chart#80]
i try webtrees 2.1.1 with your module in 2.3.0 and i have this error:

```
_Call to undefined method Fisharebest\Webtrees\Module\WebtreesTheme::parameter() …\modules_v4\webtrees-fan-chart\src\Module.php:386

#0 …\modules_v4\webtrees-fan-chart\src\Module.php(236): MagicSunday\Webtrees\FanChart\Module->getColor(Object(Cissee\WebtreesExt\IndividualExt))
#1 …\modules_v4\webtrees-fan-chart\src\Module.php(199): MagicSunday\Webtrees\FanChart\Module->getChartParameters(Object(Cissee\WebtreesExt\IndividualExt))
#2 …\app\Http\Middleware\RequestHandler.php(54): MagicSunday\Webtrees\FanChart\Module->handle(Object(Nyholm\Psr7\ServerRequest))
#3 …\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#4 …\modules_v4\vesta_research_suggestions\ResearchSuggestionsModule.php(273): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))_
```

Thanks

**Comment by magicsunday** [comment]
I found the time to build a new release for Webtrees 2.1.
