### ISSUE TITLE
error: Undefined array key

### ISSUE THREAD

**Issue by hartenthaler** [magicsunday/webtrees-fan-chart#84]
In my error log I found several error messages resulted in access from some IP addresses in the Internet (maybe a search crawler?):
`Undefined array key &quot;xref&quot; …/modules_v4/webtrees-fan-chart/src/Module.php:287</b> <b>#0 …/modules_v4/webtrees-fan-chart/src/Module.php(287): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()</b> #1 …/app/Http/RequestHandlers/ModuleAction.php(85): MagicSunday\Webtrees\FanChart\Module-&gt;getUpdateAction() #2 …/app/Http/Middleware/RequestHandler.php(54): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction-&gt;handle() #3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136):`

**Comment by hartenthaler** [comment]
Thank you! Interesting - I will study your examples and will use them, too.
