### ISSUE TITLE
Just updated Webtrees to 2.1.18 and getting fatal error in module: webtrees-fan-chart

### ISSUE THREAD

**Issue by andy-vdg** [magicsunday/webtrees-fan-chart#99]
**Describe the bug**
Upgraded to 2.1.18 and am now getting a red box with: 

```
Fatal error in module: webtrees-fan-chart
Error: Call to undefined method Fisharebest\Webtrees\Registry::container() in /var/www/webtrees/modules_v4/webtrees-fan-chart/module.php:25 Stack trace: #0 /var/www/webtrees/app/Services/ModuleService.php(735): include() #1 /var/www/webtrees/app/Services/ModuleService.php(709): Fisharebest\Webtrees\Services\ModuleService::load() #2 [internal function]: Fisharebest\Webtrees\Services\ModuleService::Fisharebest\Webtrees\Services\{closure}() #3 /var/www/webtrees/vendor/illuminate/collections/Collection.php(695): array_map() #4 /var/www/webtrees/app/Services/ModuleService.php(718): Illuminate\Support\Collection->map() #5 /var/www/webtrees/app/Services/ModuleService.php(630): Fisharebest\Webtrees\Services\ModuleService->customModules() #6 /var/www/webtrees/app/Cache.php(58): Fisharebest\Webtrees\Services\ModuleService->Fisharebest\Webtrees\Services\{closure}() #7 /var/www/webtrees/vendor/symfony/cache/Adapter/ArrayAdapter.php(84): Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}() #8 /var/www/webtrees/app/Cache.php(59): Symfony\Component\Cache\Adapter\ArrayAdapter->get() #9 /var/www/webtrees/app/Services/ModuleService.php(663): Fisharebest\Webtrees\Cache->remember() #10 /var/www/webtrees/app/Services/ModuleService.php(581): Fisharebest\Webtrees\Services\ModuleService->all() #11 /var/www/webtrees/app/Http/Middleware/UseLanguage.php(82): Fisharebest\Webtrees\Services\ModuleService->findByInterface() #12 /var/www/webtrees/app/Http/Middleware/UseLanguage.php(61): Fisharebest\Webtrees\Http\Middleware\UseLanguage->languages() #13 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process() #14 /var/www/webtrees/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle() #15 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process() #16 /var/www/webtrees/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle() #17 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process() #18 /var/www/webtrees/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle() #19 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process() #20 /var/www/webtrees/app/Http/Middleware/BadBotBlocker.php(293): Middleland\Dispatcher->handle() #21 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process() #22 /var/www/webtrees/app/Http/Middleware/CompressResponse.php(71): Middleland\Dispatcher->handle() #23 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process() #24 /var/www/webtrees/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle() #25 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process() #26 /var/www/webtrees/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle() #27 /var/www/webtrees/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process() #28 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process() #29 /var/www/webtrees/app/Http/Middleware/HandleExceptions.php(89): Middleland\Dispatcher->handle() #30 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process() #31 /var/www/webtrees/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle() #32 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process() #33 /var/www/webtrees/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle() #34 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process() #35 /var/www/webtrees/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle() #36 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process() #37 /var/www/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle() #38 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process() #39 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle() #40 /var/www/webtrees/app/Webtrees.php(275): Middleland\Dispatcher->dispatch() #41 /var/www/webtrees/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch() #42 /var/www/webtrees/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest() #43 {main}
 ```

**To Reproduce**
Updated Webtrees
Updated webtrees-fan-chart via git pull

**Expected behavior**
No error message

**Screenshots**
<img width="1319" alt="image" src="https://github.com/magicsunday/webtrees-fan-chart/assets/19990167/75a11df3-d0e9-475e-8958-7db4ec975643">

<img width="2492" alt="image" src="https://github.com/magicsunday/webtrees-fan-chart/assets/19990167/f31a02c2-363f-41de-82b6-9d88d9dfc6d5">

**Desktop (please complete the following information):**
 - Browser Edge
 - Webtrees version 2.1.18
 - Version of fan chart 2.6.2
 
![image](https://github.com/magicsunday/webtrees-fan-chart/assets/19990167/f6761a9c-d0ca-4b95-8011-3a7f5f0a5a15)

**Additional context**

**Comment by magicsunday** [comment]
Hi, please use branch 2.1 together with webtrees 2.1.18

**Comment by andy-vdg** [comment]
As far as I can tell I am using 2.6.2 on branch 2.1 (see screenshot). Or am I missing something?

**Comment by magicsunday** [comment]
Your checkout does not show what branch you checked out.

Go into module directory and execute

`git checkout 2.1 && git pull`

**Comment by andy-vdg** [comment]
Already on '2.1'
Your branch is up to date with 'origin/2.1'.

**Comment by magicsunday** [comment]
Sorry. I can't reproduce your problem. The 2.1 branch does not contain a reference to `Registry::container()`. Please double check your version of webtrees (2.1.18) and the installed module version (branch 2.1 or tag 2.6.2) again.
